# -*- ruby -*-

require 'rubygems'
require 'hoe'
require 'rake/extensiontask'

# Hoe.plugin :compiler
# Hoe.plugin :gem_prelude_sucks
# Hoe.plugin :inline
# Hoe.plugin :racc
# Hoe.plugin :rcov
# Hoe.plugin :rdoc

Hoe.spec 'ruby-libstorj' do
  developer('Bryan White', 'bryanchriswhtie@gmail.com')
  self.readme_file = 'README.rdoc'
  self.history_file = 'CHANGELOG.rdoc'
  self.extra_rdoc_files = FileList['*.rdoc']
  self.extra_dev_deps << ['rake-compiler', '>= 0']
  self.spec_extras = { :extensions => ["ext/libstorj/extconf.rb"]}

  Rake::ExtensionTask.new('libstorj', spec) do |ext|
    ext.lib_dir = File.join('lib', 'libstorj')
  end
end

Rake::Task[:test].prerequisites << :compile

# vim: syntax=ruby
